[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azuraforge-api"
version = "0.1.0"
description = "The API server for the AzuraForge Platform."
requires-python = ">=3.8"

dependencies = [
    "azuraforge-learner @ git+https://github.com/AzuraForge/learner.git@main",
    "azuraforge-worker @ git+https://github.com/AzuraForge/worker.git@main", # Worker bağımlılığı, streaming için şart
    "azuraforge-applications @ git+https://github.com/AzuraForge/applications.git@main",
    "fastapi", "uvicorn[standard]", "pydantic-settings", "python-dotenv", "pyyaml",

]

[project.scripts]
start-api = "azuraforge_api.main:run_server"
